Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

   config.vm.provision "shell", inline: <<-SHELL

  apt-get update && apt-get install -y python3-pip python3-dev
  pip3 install --upgrade pip
  pip3 install psycopg2-binary django

   SHELL

   config.vm.provision "file", source: '../../emptyfile', destination: "/tmp/emptyfile"

end